import { Topic, DiagnosticQuestion, RoadmapLesson, UserProfile, Achievement, ActivityItem } from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'user-demo-alex',
  name: 'Alex Morgan',
  email: 'alex.morgan@demo.learnx.ai',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  subject: 'math',
  subjectName: 'Mathematics',
  level: 'Intermediate',
  goal: 'Master a subject',
  dailyStudyMinutes: 30,
  overallMastery: 68,
  todayGoalActivities: 2,
  todayCompletedActivities: 1,
  currentStreak: 3,
  totalStudyHours: 14.5,
  lessonsCompleted: 8,
  quizAccuracy: 78,
  topicsMastered: 3,
  joinedDate: 'September 2026',
};

export const DEMO_TOPICS: Topic[] = [
  {
    id: 'algebra',
    subjectId: 'math',
    name: 'Algebra',
    category: 'Foundations',
    mastery: 82,
    status: 'strong',
    description: 'Manipulating algebraic expressions, polynomial operations, and factor trees.',
    whyItMatters: 'Forms the foundational syntax for all computational calculus and data analysis.',
    estimatedHours: 4,
    recommendedLessons: ['Advanced Polynomial Factoring', 'Exponent Rules Review'],
    prerequisites: ['Arithmetic'],
  },
  {
    id: 'linear-equations',
    subjectId: 'math',
    name: 'Linear Equations',
    category: 'Foundations',
    mastery: 80,
    status: 'strong',
    description: 'Single and multivariable linear relationships, slope-intercept form, and intersection points.',
    whyItMatters: 'Essential for linear regression in machine learning, economics, and circuit design.',
    estimatedHours: 3,
    recommendedLessons: ['Systems of Linear Equations', 'Matrix Representation'],
    prerequisites: ['Algebra'],
  },
  {
    id: 'functions',
    subjectId: 'math',
    name: 'Functions & Relations',
    category: 'Core Analysis',
    mastery: 45,
    status: 'developing',
    description: 'Domain, range, mappings, composite functions, and invertible transformations.',
    whyItMatters: 'Functions are the fundamental abstractions of computer programming, physical models, and calculus.',
    estimatedHours: 5,
    recommendedLessons: [
      'Functions Fundamentals & Notation',
      'Understanding Domain & Range Constraints',
      'Function Composition & Inverses',
    ],
    prerequisites: ['Algebra', 'Linear Equations'],
  },
  {
    id: 'quadratic-equations',
    subjectId: 'math',
    name: 'Quadratic Equations',
    category: 'Core Analysis',
    mastery: 25,
    status: 'weak',
    description: 'Parabolic curves, quadratic formula, vertex form, and discriminant analysis.',
    whyItMatters: 'Governs projectile motion, signal optimization, cost minimization, and physical wave fronts.',
    estimatedHours: 6,
    recommendedLessons: [
      'Introduction to Quadratics & Geometric Intuition',
      'Solving Quadratic Equations by Factoring',
      'The Quadratic Formula & Discriminant Deep Dive',
      'Graphing Parabolas & Finding Vertices',
    ],
    prerequisites: ['Algebra', 'Functions & Relations'],
  },
  {
    id: 'statistics',
    subjectId: 'math',
    name: 'Basic Statistics',
    category: 'Data & Probability',
    mastery: 72,
    status: 'strong',
    description: 'Central tendency (mean, median, mode), variance, and standard deviation distributions.',
    whyItMatters: 'Crucial for understanding experimental results, AI model evaluation, and financial forecasting.',
    estimatedHours: 4,
    recommendedLessons: ['Normal Distributions & Z-Scores', 'Hypothesis Testing Basics'],
    prerequisites: ['Algebra'],
  },
];

export const DIAGNOSTIC_QUESTIONS: DiagnosticQuestion[] = [
  {
    id: 'diag-1',
    topicId: 'algebra',
    topicName: 'Algebra',
    question: 'Simplify the algebraic expression: 3(2x - 4) + 5x - 2',
    codeOrFormula: '3(2x - 4) + 5x - 2',
    options: [
      { id: 'a', text: '11x - 14', isCorrect: true },
      { id: 'b', text: '11x - 6', isCorrect: false, misconception: 'Forgot to distribute 3 to the -4' },
      { id: 'c', text: '6x - 14', isCorrect: false, misconception: 'Missed adding the +5x term' },
      { id: 'd', text: '11x - 10', isCorrect: false, misconception: 'Subtracted 2 incorrectly from 12' },
    ],
    explanation: 'Distribute 3: 3(2x) - 3(4) = 6x - 12. Then combine like terms: 6x + 5x = 11x, and -12 - 2 = -14. Result: 11x - 14.',
  },
  {
    id: 'diag-2',
    topicId: 'linear-equations',
    topicName: 'Linear Equations',
    question: 'What is the slope of a line perpendicular to y = -2x + 5?',
    codeOrFormula: 'y = -2x + 5',
    options: [
      { id: 'a', text: '1/2', isCorrect: true },
      { id: 'b', text: '-2', isCorrect: false, misconception: 'Kept parallel slope instead of perpendicular' },
      { id: 'c', text: '2', isCorrect: false, misconception: 'Forgot the negative reciprocal rule' },
      { id: 'd', text: '-1/2', isCorrect: false, misconception: 'Took reciprocal without flipping the sign' },
    ],
    explanation: 'Perpendicular lines have slopes that are negative reciprocals: m_perp = -1 / m. Since m = -2, -1 / (-2) = 1/2.',
  },
  {
    id: 'diag-3',
    topicId: 'functions',
    topicName: 'Functions',
    question: 'What is the domain of the real-valued function f(x) = 1 / √(x - 4)?',
    codeOrFormula: 'f(x) = \\frac{1}{\\sqrt{x - 4}}',
    options: [
      { id: 'a', text: 'x > 4', isCorrect: true },
      { id: 'b', text: 'x ≥ 4', isCorrect: false, misconception: 'Dividing by zero occurs at x = 4' },
      { id: 'c', text: 'All real numbers x ≠ 4', isCorrect: false, misconception: 'Ignored the square root requiring non-negative values' },
      { id: 'd', text: 'x < 4', isCorrect: false, misconception: 'Reversed the inequality' },
    ],
    explanation: 'The term under the radical must be positive (x - 4 ≥ 0) and cannot equal zero because it is in the denominator. Therefore, x - 4 > 0, which means x > 4.',
  },
  {
    id: 'diag-4',
    topicId: 'functions',
    topicName: 'Functions',
    question: 'If f(x) = 2x + 1 and g(x) = x², what is (f ∘ g)(3)?',
    codeOrFormula: '(f \\circ g)(3) = f(g(3))',
    options: [
      { id: 'a', text: '19', isCorrect: true },
      { id: 'b', text: '49', isCorrect: false, misconception: 'Evaluated g(f(3)) instead of f(g(3))' },
      { id: 'c', text: '18', isCorrect: false, misconception: 'Forgot to add the constant 1' },
      { id: 'd', text: '25', isCorrect: false, misconception: 'Arithmetic error in evaluating composite' },
    ],
    explanation: 'First evaluate inside: g(3) = 3² = 9. Then evaluate outer: f(9) = 2(9) + 1 = 18 + 1 = 19.',
  },
  {
    id: 'diag-5',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    question: 'What are the roots of the quadratic equation x² - 5x + 6 = 0?',
    codeOrFormula: 'x^2 - 5x + 6 = 0',
    options: [
      { id: 'a', text: 'x = 2 and x = 3', isCorrect: true },
      { id: 'b', text: 'x = -2 and x = -3', isCorrect: false, misconception: 'Confused factor signs (x-2)(x-3) with roots' },
      { id: 'c', text: 'x = 1 and x = 6', isCorrect: false, misconception: 'Used factors of 6 that add to 7 instead of 5' },
      { id: 'd', text: 'x = -1 and x = 6', isCorrect: false, misconception: 'Sign mismatch in middle coefficient' },
    ],
    explanation: 'Factoring: (x - 2)(x - 3) = 0. Setting each factor to zero yields x = 2 or x = 3.',
  },
  {
    id: 'diag-6',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    question: 'What is the x-coordinate of the vertex of the parabola y = 2x² - 8x + 3?',
    codeOrFormula: 'y = 2x^2 - 8x + 3',
    options: [
      { id: 'a', text: 'x = 2', isCorrect: true },
      { id: 'b', text: 'x = -2', isCorrect: false, misconception: 'Forgot the negative sign in -b / (2a)' },
      { id: 'c', text: 'x = 4', isCorrect: false, misconception: 'Forgot to multiply the denominator by 2a' },
      { id: 'd', text: 'x = 1', isCorrect: false, misconception: 'Arithmetic error' },
    ],
    explanation: 'The vertex formula is x = -b / (2a). Here a = 2, b = -8. So x = -(-8) / (2 * 2) = 8 / 4 = 2.',
  },
  {
    id: 'diag-7',
    topicId: 'statistics',
    topicName: 'Basic Statistics',
    question: 'Given the dataset [4, 8, 6, 5, 3, 4, 12], what is the median?',
    codeOrFormula: '\\text{Data: } [4, 8, 6, 5, 3, 4, 12]',
    options: [
      { id: 'a', text: '5', isCorrect: true },
      { id: 'b', text: '4', isCorrect: false, misconception: 'Found the mode instead of the median' },
      { id: 'c', text: '6', isCorrect: false, misconception: 'Did not sort the array before picking middle' },
      { id: 'd', text: '6.0', isCorrect: false, misconception: 'Calculated the mean instead of median' },
    ],
    explanation: 'Sort data in ascending order: [3, 4, 4, 5, 6, 8, 12]. With 7 items, the middle 4th item is 5.',
  },
];

export const DEMO_ROADMAP: RoadmapLesson[] = [
  {
    id: 'lesson-1',
    week: 1,
    order: 1,
    title: 'Functions Fundamentals & Mapping',
    topicId: 'functions',
    topicName: 'Functions',
    durationMinutes: 20,
    completed: true,
    type: 'concept',
    description: 'Learn what constitutes a formal mathematical relation versus a well-defined function.',
    summaryPoints: [
      'Every input in the domain maps to exactly ONE output.',
      'The vertical line test geometrically validates functions.',
      'Function notation f(x) denotes output value at variable x.',
    ],
    interactivePractice: {
      question: 'Which of the following relations represents a valid function?',
      options: [
        '{(1, 2), (2, 4), (3, 6)}',
        '{(1, 2), (1, 5), (2, 8)}',
        'A vertical line x = 4',
        'A circle centered at (0,0)',
      ],
      correctIndex: 0,
      explanation: 'In {(1, 2), (2, 4), (3, 6)}, every unique x-value pairs with exactly one y-value.',
    },
  },
  {
    id: 'lesson-2',
    week: 1,
    order: 2,
    title: 'Understanding Domain & Range',
    topicId: 'functions',
    topicName: 'Functions',
    durationMinutes: 15,
    completed: false,
    type: 'concept',
    description: 'Identify real-number boundaries, radical restrictions, and denominator exclusion points.',
    summaryPoints: [
      'Denominator cannot equal zero (f(x) = 1/x -> x ≠ 0).',
      'Even radicals require non-negative radicands (√x -> x ≥ 0).',
      'Interval notation: brackets [ ] include endpoints, parentheses ( ) exclude them.',
    ],
    interactivePractice: {
      question: 'What is the domain of f(x) = √(x - 5)?',
      options: ['x ≥ 5', 'x > 5', 'x ≤ 5', 'All real numbers'],
      correctIndex: 0,
      explanation: 'Under an even square root, the expression must be greater than or equal to zero: x - 5 ≥ 0 -> x ≥ 5.',
    },
  },
  {
    id: 'lesson-3',
    week: 1,
    order: 3,
    title: 'Functions Practice Quiz',
    topicId: 'functions',
    topicName: 'Functions',
    durationMinutes: 10,
    completed: false,
    type: 'quiz',
    description: 'Targeted evaluation testing your mastery of function constraints before moving to quadratics.',
    summaryPoints: [
      'Adaptive 5-question test.',
      'Identifies lingering edge cases in fractional domains.',
      'Rewards +17% topic mastery upon passing.',
    ],
  },
  {
    id: 'lesson-4',
    week: 2,
    order: 1,
    title: 'Introduction to Quadratics & Parabolas',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    durationMinutes: 20,
    completed: false,
    type: 'concept',
    description: 'Explore the geometric curve of f(x) = ax² + bx + c and discover why symmetry creates two roots.',
    summaryPoints: [
      'The coefficient "a" controls steepness and whether the parabola opens up or down.',
      'The line of symmetry passes directly through the vertex.',
      'Roots are the x-intercepts where y = 0.',
    ],
    interactivePractice: {
      question: 'If a > 0 in y = ax² + bx + c, does the vertex represent a minimum or maximum point?',
      options: ['Minimum', 'Maximum', 'Inflection point', 'Undefined'],
      correctIndex: 0,
      explanation: 'When "a" is positive, the parabola opens upwards, making the vertex the lowest (minimum) point.',
    },
  },
  {
    id: 'lesson-5',
    week: 2,
    order: 2,
    title: 'Solving Quadratic Equations by Factoring',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    durationMinutes: 25,
    completed: false,
    type: 'practice',
    description: 'Master reverse FOIL factoring, difference of squares, and zero-product properties.',
    summaryPoints: [
      'If A * B = 0, then either A = 0 or B = 0.',
      'Find two integers p and q such that p*q = c and p+q = b.',
      'Difference of squares: a² - b² = (a - b)(a + b).',
    ],
  },
  {
    id: 'lesson-6',
    week: 2,
    order: 3,
    title: 'Adaptive Assessment & Mastery Benchmark',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    durationMinutes: 10,
    completed: false,
    type: 'checkpoint',
    description: 'Comprehensive adaptive assessment benchmarking algebra, functions, and quadratic problem-solving.',
    summaryPoints: [
      'Dynamic difficulty adjustment.',
      'Unlocks Week 3 advanced polynomial curve sketching.',
    ],
  },
];

export const ADAPTIVE_QUIZ_SET = [
  {
    id: 'quiz-q1',
    topic: 'Functions & Relations',
    question: 'What is the domain of f(x) = (2x + 1) / (x - 3)?',
    options: [
      'All real numbers except x = 3',
      'x > 3',
      'All real numbers except x = -1/2',
      'All real numbers',
    ],
    correctIndex: 0,
    misconceptionExplanation: 'The denominator x - 3 cannot equal 0. Setting x - 3 = 0 gives x = 3, so x = 3 is the only excluded value. The numerator does not restrict the domain.',
  },
  {
    id: 'quiz-q2',
    topic: 'Functions & Relations',
    question: 'If f(x) = x² - 4, what is the Range of f(x)?',
    options: [
      '[-4, ∞)',
      '(-∞, ∞)',
      '[0, ∞)',
      '(-4, 4)',
    ],
    correctIndex: 0,
    misconceptionExplanation: 'Since x² ≥ 0 for all real numbers x, the minimum value occurs at x = 0, where f(0) = 0 - 4 = -4. Thus, outputs can reach -4 or any value above.',
  },
  {
    id: 'quiz-q3',
    topic: 'Functions & Relations',
    question: 'Given h(x) = 3x - 5, what is the inverse function h⁻¹(x)?',
    options: [
      'h⁻¹(x) = (x + 5) / 3',
      'h⁻¹(x) = 3x + 5',
      'h⁻¹(x) = 1 / (3x - 5)',
      'h⁻¹(x) = (x - 5) / 3',
    ],
    correctIndex: 0,
    misconceptionExplanation: 'To find the inverse, swap x and y: x = 3y - 5. Add 5 to both sides: x + 5 = 3y. Divide by 3: y = (x + 5) / 3.',
  },
  {
    id: 'quiz-q4',
    topic: 'Quadratic Equations',
    question: 'What is the discriminant of the quadratic equation 2x² + 4x - 6 = 0?',
    options: [
      '64',
      '32',
      '-32',
      '16',
    ],
    correctIndex: 0,
    misconceptionExplanation: 'The discriminant is Δ = b² - 4ac. Here a = 2, b = 4, c = -6. So Δ = (4)² - 4(2)(-6) = 16 - (-48) = 16 + 48 = 64. A positive discriminant indicates two distinct real roots.',
  },
  {
    id: 'quiz-q5',
    topic: 'Functions & Relations',
    question: 'If f(x) = 3x and g(x) = x + 2, what is g(f(2))?',
    options: [
      '8',
      '12',
      '10',
      '14',
    ],
    correctIndex: 0,
    misconceptionExplanation: 'First evaluate inside: f(2) = 3(2) = 6. Then evaluate outer: g(6) = 6 + 2 = 8. Common misconception is doing f(g(2)) which would give 3(4) = 12.',
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Lesson',
    icon: '🏆',
    description: 'Completed your first personalized interactive concept lesson.',
    unlocked: true,
    unlockedAt: '2 days ago',
    progress: 1,
    maxProgress: 1,
  },
  {
    id: 'ach-2',
    title: '3 Day Streak',
    icon: '🔥',
    description: 'Studied consistently 3 days in a row without breaking focus.',
    unlocked: true,
    unlockedAt: 'Today',
    progress: 3,
    maxProgress: 3,
  },
  {
    id: 'ach-3',
    title: 'Concept Master',
    icon: '🧠',
    description: 'Achieved >80% mastery in Algebra and Linear Equations.',
    unlocked: true,
    unlockedAt: 'Yesterday',
    progress: 2,
    maxProgress: 2,
  },
  {
    id: 'ach-4',
    title: 'Quiz Master',
    icon: '🎯',
    description: 'Score 80%+ on an adaptive quiz targeting weak areas.',
    unlocked: true,
    unlockedAt: '3 days ago',
    progress: 1,
    maxProgress: 1,
  },
  {
    id: 'ach-5',
    title: 'Fast Learner',
    icon: '🚀',
    description: 'Raised a developing topic mastery score by more than 15% in one session.',
    unlocked: true,
    unlockedAt: '1 day ago',
    progress: 1,
    maxProgress: 1,
  },
  {
    id: 'ach-6',
    title: '10 Lessons Completed',
    icon: '⭐',
    description: 'Complete 10 roadmap lessons across your curriculum.',
    unlocked: false,
    progress: 8,
    maxProgress: 10,
  },
  {
    id: 'ach-7',
    title: 'Curriculum Conqueror',
    icon: '👑',
    description: 'Attain an overall mastery score above 85%.',
    unlocked: false,
    progress: 68,
    maxProgress: 85,
  },
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    title: 'Completed Algebra Quiz',
    subtitle: 'Score: 5/5 (100%) • Topic benchmark verified',
    timestamp: '2 hours ago',
    icon: '🎯',
    type: 'quiz',
  },
  {
    id: 'act-2',
    title: 'Learned Functions Fundamentals',
    subtitle: 'Completed 20 min lesson on relations & vertical line test',
    timestamp: 'Yesterday at 4:15 PM',
    icon: '📘',
    type: 'lesson',
  },
  {
    id: 'act-3',
    title: 'Improved mastery by 8%',
    subtitle: 'Functions & Relations score elevated from 37% to 45%',
    timestamp: 'Yesterday at 4:40 PM',
    icon: '📈',
    type: 'mastery',
  },
  {
    id: 'act-4',
    title: '3-Day Study Streak Maintained',
    subtitle: 'Daily target of 30 minutes achieved',
    timestamp: 'Today at 9:00 AM',
    icon: '🔥',
    type: 'streak',
  },
];

export const WEEKLY_PROGRESS_DATA = [
  { day: 'Mon', hours: 0.8, mastery: 61, score: 70 },
  { day: 'Tue', hours: 0.6, mastery: 63, score: 75 },
  { day: 'Wed', hours: 1.1, mastery: 65, score: 80 },
  { day: 'Thu', hours: 0.9, mastery: 66, score: 78 },
  { day: 'Fri', hours: 1.3, mastery: 68, score: 85 },
  { day: 'Sat', hours: 0.5, mastery: 68, score: 82 },
  { day: 'Sun', hours: 0.8, mastery: 72, score: 88 },
];

export const ROADMAP_MILESTONES = [
  {
    id: 'mile-1',
    phase: 'Phase 1: Foundations',
    title: 'Linear Equations & Slope Review',
    topicId: 'linear-equations',
    topicName: 'Linear Equations',
    estimatedTime: '20 mins',
    status: 'completed' as const,
    description: 'Review slope-intercept form, perpendicular slopes, and linear intersection modeling.',
  },
  {
    id: 'mile-2',
    phase: 'Phase 1: Foundations',
    title: 'Functions Introduction & Vertical Line Test',
    topicId: 'functions',
    topicName: 'Functions',
    estimatedTime: '25 mins',
    status: 'completed' as const,
    description: 'Learn input-output mapping criteria and identify relations that qualify as mathematical functions.',
  },
  {
    id: 'mile-3',
    phase: 'Phase 2: Core Concepts',
    title: 'Domain & Range Constraints (Weak Area Fix)',
    topicId: 'functions',
    topicName: 'Functions',
    estimatedTime: '15 mins',
    status: 'in_progress' as const,
    description: 'Targeted micro-lesson addressing the root/denominator restriction misconception.',
  },
  {
    id: 'mile-4',
    phase: 'Phase 2: Core Concepts',
    title: 'Quadratic Equations & Geometric Roots',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    estimatedTime: '30 mins',
    status: 'next' as const,
    description: 'Visualize parabolic trajectories and master algebraic factoring techniques.',
  },
  {
    id: 'mile-5',
    phase: 'Phase 3: Advanced Applications',
    title: 'The Quadratic Formula & Discriminant Analysis',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    estimatedTime: '25 mins',
    status: 'locked' as const,
    description: 'Master determining real vs complex roots using b² - 4ac before solving.',
  },
  {
    id: 'mile-6',
    phase: 'Phase 3: Advanced Applications',
    title: 'Graphing Parabolas & Real-World Optimization',
    topicId: 'quadratic-equations',
    topicName: 'Quadratic Equations',
    estimatedTime: '35 mins',
    status: 'locked' as const,
    description: 'Calculate vertex maxima and minima to model physics and profit curve problems.',
  },
];

export const TOPICS_DATA = DEMO_TOPICS;
export const ACHIEVEMENTS_DATA = INITIAL_ACHIEVEMENTS;

